c=1e-5*k+1e-4*m;
nummode=9;
Omega=0:0.01:3000;
p=8; 
q=2;
[Hd,Hv,Ha]=freqresponse(k,m,c,Omega,nummode,'all',p,q)
figure(1)
plot(Omega,log(abs(Hd)))
xlabel('Omega(Hz)')
ylabel('Hd')
figure(2)
plot(Omega,log(abs(Hv)))
xlabel('Omega(Hz)')
ylabel('Hv')
figure(3)
plot(Omega,log(abs(Ha)))
xlabel('Omega(Hz)')
ylabel('Ha')
